### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by sarahvc**
1. Added responsive behavior: Set the amount of page buttons' maximum to 3 when screen is under 768px.
2. Added hover pointer to page buttons.

### CODE REVIEW

**Comment by antelopeb** [comment]
I'm not seeing the responsiveness working on my end:
image

Can you check to make sure that it is all working as expected? I'm testing in Chrome latest.

Also, the last item on the testing page, "Compact type", isn't working at all when clicked. Please verify.

**Comment by sarahvc** [comment]
@antelopeb Just checked. The responsiveness is working on my end. The last compact type is not working for me too, and it's also not working on master branch. Probably some bug with the demo page, I'll check and fix it.

**Comment by antelopeb** [comment]
Derp. I was on the wrong branch... Working perfectly now. Let me know when the compact type is fixed and I will merge.

**Comment by sarahvc** [comment]
@antelopeb Should be good now. I made changes to the paginationContainer.js to update the text inside the compact pagination when user clicks on it.

**Pull request merged**
