### PR TITLE
Feature/reskin

### PR DESCRIPTION
**Pull request by nlkluth**
reskin of pagination component for console

### CODE REVIEW

**Comment by umahaea** [comment]
@kiran - I think it needs some styling tests to be added.

**Comment by nlkluth** [comment]
@umahaea is this good to merge?

**Comment by umahaea** [comment]
No @nlkluth - Can you ask you QA to add tests for this change?.... It will break regression when we merge.

**Comment by umahaea** [comment]
Tests are written and reviewed. Good to merge.

**Pull request merged**
