### PR TITLE
chore: this will add repo specific tokens for travis

### PR DESCRIPTION
**Pull request by JasonLantz**

### CODE REVIEW

**Comment by nlkluth** [comment]
Sweet thanks! Do we approve this, or someone else? 😃

**Comment by JasonLantz** [comment]
i left it for your team to approve and merge....

you can see the ci running here:
https://travis-ci.org/Pearson-Higher-Ed/pagination

**Comment by umahaea** [comment]
@nlkluth - We need java selenium tests for every origami component. This is as per the governance policy. Please ask QA in your team to write those tests. Payal has already demoed to them on how and where to write the tests. PDA QA will review the Selenium tests PR.

**Comment by nlkluth** [comment]
Great, thanks!

**Pull request merged**
